#let question = (
  "A": [
    To what extent does the hardware platform #footnote[Server, PC, and Raspberry Pi] impacts the energy efficiency of code generated by LLMs? See footnotes #footnote[Even tho this is not an explicit research question in the paper, the impact of the hardware platform is a recurring theme of this research.].
  ],
  "B": [
    When developers use LLMs to write code, we usually assume that if the code works, it will behave similarly no matter where it runs. However, different hardware architectures handle code instructions differently. This research question investigates if code that is energy efficient on a high-end server is still energy efficient when deployed on an everyday PC or a resource constrained IoT device like a Raspberry Pi.

    Billions of lines of AI-generated code are being pushed into production environments globally. If an LLM generates a script that runs perfectly on a developer's local PC but suddenly wastes massive amounts of electricity when running on a remote servers, it leads to huge financial costs and a larger environmental footprint.
  ],
  "C": [
    To answer this specific RQ the researchers run all tests on three physical machines with very differnt hardware specs. The machines were a high-end server, a PC, and a Raspberry Pi. To make sure they were measuring only the code's energy and not background noise, they turned off all non-essential background processes, set the CPU power governor to performance, and a cooldown period of 60 second between tests so the machines wouldn't overheat and alter results. They executed each piece of code 21 times per machine (discarding the first run to avoid cold starts). Because the scripts run very quickly, they wrapped the functions in loops and subtracted the energy of an "empty pass" function to isolate the code's precise consumption. They recorded energy consumption using EnergiBridge for a total of approximately 4.6 billion energy measures. The authors ran a statistical test called a (ART) ANOVA. This specific test allowed them to see if the interaction between the Model used and the Hardware platform was statistically significant. The researchers also tried to nodge LLMs into a more appropriate solution for the platform by telling to the AI the hardware profile the code was going to be execute on, but as @eec_via_llms - $R Q_2$ shown prompt engineering does not have a significant impact on energy consumption sometimes even getting worse results.
  ],
  "D": (
    "1": [
      Instead of measuring physical power usage on real machines, the authors could have used profiling tools like `perf` to track micro-architectural metrics like cache misses and branch mispredictions. These micro-architectural metrics could also be obtained by running the LLM-generated code inside specialized software simulators (like GEM5) that supports different CPU instruction set architectures (e.g. x86 or ARM) and configurable memory. Testing on real hardware gives you actual, authentic physical data reflecting real world usage. However, it suffers from a lot of unpredictable hardware noise. It is also incredibly slow and expensive to test, and does not generalize well to future hardware. On the other hand the proposed alternative completely isolates the software. It can tell you exactly why a piece of code is draining power by tracking microscopic variables (e.g., "this nested loop caused 5,000 L1 cache misses on ARM but only 200 on x86"). It is 100% repeatable with zero environment noise. The downside is that the results are software approximations and they do not capture the chaotic nature of a real world systems.
    ],
    "2": [
      In @pinto_efficiency_2014, on their research on software energy consumption, instead of just tracking raw system power, they utilized micro-architectural profiling metrics like context switches and OS thread overhead to explain the exact hardware mechanics causing code to use more energy.
    ],
  ),
)
