#let question = (
  "A": [
    "What is the difference between code developed by a Green software expert and LLM-generated code in terms of energy efficiency?" @eec_via_llms - $R Q_3$
  ],
  "B": [
    As more developers rely on AI tools to produce code faster, the volume of code that is generated and deployed is also likely to increase. This makes it important to evaluate code not only for functional correctness, but also for non-functional qualities such as energy efficiency. In many cases, developers focus primarily on functionality and may overlook sustainability concerns. Therefore, it is valuable to understand how LLM-generated code compares with code written by a Green software expert in terms of energy efficiency, since this can have significant implications for the sustainability of software applications and the environment.
  ],
  "C": [
    The authors utilized an Empirical Style, such that they first setup a controlled experimental environment to execute code across different hardware platforms. Following standard methodological definitions (Bhattacherjee, 2012 @bhattacherjee_social_science_2012), the proposition claims a relationship bewtween two constructs: code and energy efficiency. To test this proposition, the hypothesis is that the expert-written code consumes less energy than the LLM-generated code. The moderating variable is represented by three different hardware platforms: server, laptop, and Raspberry Pi.
    They selected a set 9 coding problems from the EvoEval benchmark, motivated by @xia_top_leaderboard_2024, but focused on specifically 4 of these for the green software expert and LLM-generated code comparison. For AI generation, they used 6 different LLMs combined with 4 distinct prompting strategies. In regards to the green software expert, a specialist with over 7 years of experience manually optimized the code using the problem description, the canonical solutions, test cases and a set of specially curated guidelines.
    Finally, to measure the dependent variable, defined as energy consumption in Joules, the researchers executed each solution for approximately 3 minutes. They repeated these measurements 21 times on each hardware platform to account for intrinsic energy fluctuations and to strengthen the statistical power.
  ],
  "D": (
    "1": [
      An alternative method the authors could have used is a Taxonomical Style, where they could have focused on the structural analysis of the source code generated by both the Green software expert and the LLMs. So, instead of setting up an experimental environment to measure energy consumption, the code could be evaluated based on structural features that are known to influence energy efficiency, such as data structures, algorithmic complexity, and design patterns.
      The fundamental trade-off between the original method and this alternative is that the physical execution provide a direct measurement of energy consumption, which is a more concrete and empirical approach. In contrast, the taxonomical method relies on theoretical analysis. By classifying and labeling the code based on its structural features, the risk is that it may not capture the real-world energy consumption accurately.
    ],
    "2": [
      Literature support can be found at @haoli_mobile_consumption_2013.
    ],
  ),
)
