#let question = (
  "A": [
    "What is the difference between human code and LLM-generated code in terms of energy-efficiency?" #box[(@eec_via_llms - $R Q_1$)]
  ],
  "B": [
    In software creation, tools that use LLMs to generate code are used more often by new and experienced developers.
    These tools are increasingly replacing code that would have been human-written.
    Therefore, the relevant question is whether this shift improves or worsens energy consumption.
    Human-written code is the logical place of comparison, as it represents what LLM-generated code is replacing in practice.

    Before this paper, research was mainly focused on the performance, readability, and maintainability of LLM-generated code. Energy efficiency has received (far less) attention in prior research, while software sustainability and Green AI are becoming more important in research and industry.
    If LLM-generated code is systematically less energy-efficient than code by human developers, then widespread adoption of tools using these LLMs leads to large-scale energy waste.
    Before being able to investigate $R Q_2$ and $R Q_3$, we first must understand how LLM-generated code performs relative to human-written code ($R Q_1$), as a baseline.
    Answering this question shows whether a gap in energy efficiency exists between human-written and LLM-generated code. If such a gap exists, it shows that efforts should be made to improve the energy efficiency of LLM-generated code.
    If not, then the industry can rely on LLMs without concerns about energy waste.
  ],
  "C": [
    The authors use a quantitative, empirical research design structured as a controlled experiment.
    The study design follows guidelines for empirical software engineering @shull_guide_2008 @wohlin_experimentation_2014 and energy efficiency assessment @achim_development_2024 @garcia_process_2021.

    The independent variable is the origin of the code. This can be either human-written or generated by an LLM. The dependent variable is the energy consumption used by the solution.
    The energy consumption can differ between machines. Therefore, experiments are conducted over various hardware: a server, a pc, and a Raspberry Pi.

    The human baseline comprises the canonical solutions in the EvoEval benchmark.
    The functional solutions are the LLM-generated solutions. These solutions are generated by six selected LLMs, using the original EvoEval prompt, without any prompt modification related to energy efficiency.

    Each solution variant is executed 21 times on each platform to factor out random occurrences. The EnergiBridge measuring software is used to measure energy consumption on the server and PC. For the Raspberry Pi, this is Monsoon Power Monitor.
  ],
  "D": (
    "1": [
      The canonical solutions from EvoEval are only a single implementation per problem: the details of the writer and the environment in which it was produced are unknown. The human side of comparison is therefore small and maybe unrepresentative.
      An alternative is to recruit multiple developers and let them independently solve the same problem. Varying in experience, coding style, and optimization skills to generalize more.
      Downside is that recruiting is very time-consuming (as Justus Bogner stated in his guest lecture), adds confounding factors (program language proficiency differences, energy-efficiency awareness), which are avoided by canonical solutions.
      Dilemma: canonical solutions have higher reproducibility (you can take the exact same solutions in a retry) but lower representativeness. Recruiting developers reflects real-world conditions better but has lower experimental control.
    ],
    "2": [
      A recent study using the alternative method is Wang et al. @wang_rocks_2024, who used this approach in comparing different LLMs on software engineering tasks. They recruited 109 developers with at least one year of professional developer experience to independently solve coding tasks.
      Moreover, a foundational study by Prechelt @prechelt_empirical_2000 uses a similar style. In this study, 80 programmers implemented the same problem independently. An important finding from this paper is that the variation between programmers in the same language was often bigger than variation between languages. This shows that a single canonical solution from EvoEval might not represent how different programmers approach the same problem.
    ],
  ),
)
