#let question = (
  "A": [
    "How does the energy efficiency of LLM-generated code vary when using different LLMs?" @eec_via_llms - $R Q_0$
  ],
  "B": [
    Our main objective is to find out how energy efficient the code written by LLMs is, by comparing LLM-generated code with human-generated code and code generated by a Green software expert. However, it is important to also do a comparison between the LLM models themselves, before transitioning to comparison with a human or a Green software expert. Answering this question will help us with setting the context of the experiment, to see if there is any energy consumption difference between the code generated by different models. This helps with seeing if the LLMs can be seen as a general, singular subject for comparison - meaning that all the models produce the same results in terms of energy consumption -, or if each of them produces different results, because after all, each LLM model is structured and trained differently.

    From a *practical* standpoint, this is important especially for the developers community, which nowadays, are increasingly using LLMs for writing code not just as a tool, but as an assistant. We also aim to compare the energy efficiency of the LLM-generated code on multiple hardware platforms: a server, a PC, and a Raspberry Pi. Based on the results we will have, a developer can make an optimal choice in terms of energy efficiency when using an LLM as a coding assistant, depending on the hardware context in which they are working.

    From a *theoretical* standpoint, we want to cover a less explored attribute for evaluating the quality of LLM-generated code. So far, evaluations of code generated this way consisted of only checking the correctness, i.e., the code produces the right output for a given problem. With the analysis of energy consumption, we can now think of a new way to evaluate LLMs. Moreover, we will also obtain a better perspective over how different models, having different architectures, training methods, training datasets, and number of parameteres perform with respect to this evluation of energy efficiency. Maybe none of them were specifically trained with the purpose of generating energy-efficient code in mind, but somehow, based on the different properties mentioned earlier, they might have "inherited" this capacity.
  ],
  "C": [
    We aim to select the top 6 accessible, unique LLMs in the difficult category of the EvoVal leaderboard, as of July 2024, based on two main criteria:
    
    *Accessbility:* the model is either open-source of available through API.

    *Uniqueness:* the model uses a different base model compared to the other already-chosen LLMs.

    This will imply choosing LLMs created by different companies, such as OpenAI (ChatGPT), DeepSeek (DeepSeek), Meta (Codellama), or BudEcosystem (CodeMillenials)

    The EvoVal leadeboard was built on the HumanEval benchmark by OpenAI and includes 828 coding problems across different domains on which LLMs are evaluated based on the capacity of generating solutions for those problems @xia_top_leaderboard_2024. The reasons for choosin EvoVal as a source for the LLMs are that it is one of the most recent benchmarks for evaluating LLMs trained for code generation, and contains multiple test cases, and also a source-of-truth solution for each problem.

    This way of choice will give us a certain level of external validity, as we will have a larger variety of models in terms of architecture, sizes, and training method.

    Moving forward to the coding problem selection, we want to select 100 coding problems from the Difficult category in EvoVal, since we want to generate Python code with higher computational complexity and additional requirements compared to the other categories. We will only keep the problems for which each of the chosen LLMs generated a correct solution, since correctness will need to be already validated. We will evaluate these solutions based on the test cases we will extract from EvoVal. These initial solutions that we will test in order to see if they will provide the correct results will be the "functional solutions" representing the solutions that we will extract based on the original prompt given to each LLM, for each problem, from EvoVal.

    These original prompts that will create the functional solutions will also be used to create different types of prompts. As this is not highly relevant for this specific research question, we won't dive deeper into what these different prompts represent. If a solution generated from an LLM, for a specific prompt, proves not to be correct after 6 reprompts, that specific solution will be removed from the analysis. Once again, the solutions will be verified against the extracted test cases from EvoVal to see if they will be correct. All the remaining solutions will be executed on three hardware platforms that we chose, with the purpose of strengthening the external validity by offering results accross a wide spectrum of hardware specifications.

    We will calculate a number $X_p^m$ (m - hardware machine, p - problem) of iterations with the purpose of achieving a runtime of 3 minutes. On each machine m, all test cases will be executed for each variant of a solution to problem p for $X_p^m$ iterations. Each of these runs will be repeated 21 times on each hardware platform.
  ],
  "D": (
    "1": [
      A fundamentally different approach could consist of different choices in the following aspects of the study:
      + *LLM selection* - Choose more LLMs that vary in more different ways, not just architecture or parameters. The variety could consist of availability (open-source or closed-source) or of LLMs chosen specifically from big tech companies like Amazon, Google, or Meta. This would generalize the comparison and results even more.
      + *Problem selection* - Increase the variety once again in this aspect of the study by choosing significantly more problems that vary not only in algorithmic categories,but also in difficulty.
      + *Hardware platform selection* - Only choose one hardware platform.
      + *Energy measurement* - Instead of using tools like EnergiBridge and Monsoon, use a more accessible tool, like the `perf` Linux tool.

      The dilemma of choosing between the two methodologies is based on multiple trade-offs. Firstly, the new methodology would provide far greated external validity, as results can be questioned much easier when they are based upon a small number of LLMs or problems.

      Moreover, the original methodology is far stricter, as the final problems for the analysis are carefully selected based on whether or not each LLM generated a correct solution for them, while in this new methodology, a regeneration cycle is applied in which the LLMs are reprompted up to 25 times, and the first passing solution is considered for the analysis. This can cause unfair comparisons, as some LLMs that might manage to generate a correct solution after very few reprompts will be compared to LLMs that might have needed a lot more attempts. The first case represents an "innate" capacity of the LLM to generate a correct solution, while the second case represents more of a "learning" capacity. On the other hand, this option also allows for a much larger variety of problems to be included in the analysis. The paper's methodology might result in only the easier problems from the chosen difficult category to be selected, as those problems give higher chances to LLMs to successfully generate a correct solution on the first try. Besides this, it also doesn't represent a realistic scenario, as in the real world, developers usually keep reprompting the LLM until they get a satisfactory solution.

      Another trade-off between the two methodologies is represented by the precision of the analysis. Apsan et al.'s (the paper in question) 21 repetitions per run, combined with tools like EnergiBridge and Monsoon, yield high statistical accuracy. This new methodology includes only 5 repetitions, using the 'perf' Linux tool for the energy consumption analysis, making the execution easier to reproduce by other researchers.

      With regard to the hardware platform selection, the original methodology would be more insightful in terms of how dependable energy efficiency is on hardware platforms, providing researchers and developers with a clearer option for choosing the right LLM for the right hardware. When it comes to the new methodology, the results would provide a more general perspective, which could still be useful for most developers who simply use a company laptop, with the advantage of having a simpler experiment design by disregarding a confounding factor.
    ],
    "2": [
      Literature support can be found at @islam_evaluating_2025, in which the authors gather multiple open-source and closed-source LLMs from different companies, like Mistral, Google, Meta, or Amazon, and compare all the LLMs with each other, and also with canonical human-written solutions, in terms of the energy efficiency of the code that is produced by them. In the study, the LLMs are prompted to generate solutions for 878 programming problems that vary in difficulty and algorithmic categories, gathered from the world known platform Leetcode.
    ],
  ),
)
