#let question = (
  "A": [
    "How does the energy efficiency of LLM-generated code vary when using different LLMs?" @eec_via_llms - $R Q_0$
  ],
  "B": [
    Our main objective is to find out how energy efficient is the code written by LLMs, by comparing LLM-generated code with human-generated code and code generated by a Green
    software expert. However, it is important to also do a comparison between the LLM models themselves, before transitioning to comparison with a human or a Green software expert. Answering this
    question will help us with setting the context of the experiment, to see if there is any energy consumption difference between the code generated by different models. This helps
    with seeing if the LLMs can be seen as a general, singular subject for comparison - meaning that all the models produce the same results in terms of energy consumption -, or if each of them
    produce different results; because after all, each LLM model is structured and trained differently.

    From a *practical* standpoint, this is important especially for the developers community, which nowadays, are increasingly using LLMs for writing code not just as a tool, but as an assistant.
    We also aim to compare the energy efficiency of the LLM-generated code on multiple hardware platforms: a server, a PC, and a Raspberry Pi. Based on the results we will have,
    a developer can make an optimal choice in terms of energy efficiency when using an LLM as a coding assistant, depending on the hardware context in which he is working.

    From a *theoretical* standpoint, we want to cover a less explored attribute for evaluating the quality of LLM-generated code. So far, evaluations of code generated this way
    consisted of only checking the correctness, i.e., the code produces the right output for a given problem. With the analysis of energy consumption, we now can think of a new way to evaluate
    LLMs. Moreover, we will also obtain a better perspective over how different models, having different architectures, training methods, training datasets and number of parameteres perform with
    respect to this evluation of energy efficiency. Maybe non of them were specifically trained with the purpose of generating energy efficient code in mind, but somehow, based on the different
    properties mentioned earlier, they might have "inherited" this capacity.
  ],
  "C": [
    We aim to select the top 6 accessible, unique LLMs in the difficult category of the EvoVal leaderboard, as of July 2024, based on two main criteria: \
    *Accessbility:* the model is either open-source of available through API. \
    *Uniqueness:* the modes uses a different base model compared to the other already-chosen LLMs.

    This way of choice will give us a certain level of external validity, as we will have a larger variety of models in terms of architecture, sizes, and training method.

    Moving forward to the coding problem selection, we want to select 100 coding problems from the Difficult category in EvoVal, since we want to generate Python code with higher
    computational complexity and additional requirements compared to ther other categories. We will only keep the problems for which each of the chosen LLMs generated a correct solution, since
    correctness will need to be already validated. We will evaluate these solutions based on the test cases we will extract from EvoVal. These initial solutions that we will test in order to
    see if they will provide the correct results will be the "functional solutions", representing the solutions that we will extract based on the original prompt given to each LLM,
    for each problem, from EvoVal.

    These original prompts that will create the functional solutions will also used to create different type of prompts. As this is not highly relevant for this specific research question, we
    won't dive deeper into what these different prompts represented, but we mention the fact that they will have the purpose of generating code specific to different criteria mentioned in each
    prompt. If a solution generated from an LLM, for a specific prompt, will prove to not be correct after 6 reprompts, that specific solution will be removed from the analysis. Once again,
    the solutions will be verified against the extracted test cases from EvoVal to see if they will be correct. All the remaining solutions will be executed on all three hardware platorms that
    we chose, with the purpose of strengthening the external validity by offering results accross a wide spectrum of hardware specifications: \
    *Server:* Intel Xeon Silver 4208, 384GB RAM, Ubuntu 20.04. \
    *PC*: Intel Core i9, Nvidia RTX 4070, 64GB RAM, Ubuntu 24.04. \
    *Raspberry Pi:* (Cortex-A72 ARM v8, 8GB RAM, Raspberry Pi OS.

    We will calculate a number $X_p^m$ (m - hardware machine, p - problem) of iterations with the purpose of achieving a runtime of 3 minutes. On each machine m, all test cases will be executed
    for each variant of a solution to problem p for $X_p^m$ iterations. Each of these runs will be repeated 21 times on each hardware platform.

  ],
  "D": (
    "1": [
      Instead of generating and exeucting code in a controlled experiment, one good alternative could be to gather code from software repositories, and apply the evaluation on that. This would
      imply collecting large sampels of real-world Python code generated by each of the chosen LLMs, from publicly available sources (for example, GitHub repositories). Instead of executing the code
      the energy efficiency analysis could be done based on energy-costly code patterns (like nested loops, redundant operations, or inefficient data structured, some of which are also mentioned
      in the original paper). Deciding between the original methodology and this one could represent a dilemma because of the following facts:
      + The original methodology uses benchmark problems from EvoVal in a controlled environment. This can raise the question of how much the results would be actually applicable in the real world. This new approach would use code that developers actually developed in production, giving the result more validity. However, the experiment control is sacrificed, as using publicly available code could introduce confounding factors, like post-editing of LLM output (by the developer), or maybe false attributions of which LLM generated which code.
      + The static analysis employed in the new method allows for much more freedom in terms of time. Quantity-wise, a lot more solutions could be evaluated per LLM, however, accuracy is sacrificed compared to the original methodology.
      + A much wider range of LLMs could become available by collecting data from publicly available sources. And not just the model variety would increase, but also the variety of programming contexts. However, the possibility of also considering hardware platforms would be sacrificed, which was proved to be quite important in the findings of the paper.
    ],
    "2": [
      Literature support can be found at @kalliamvakou_promises_2014.
    ],
  ),
)
