#let question = (
  "A": [
    "What is the impact of prompt engineering techniques on the energy efficiency of LLM-generated code?" @eec_via_llms - $R Q_2$
  ],
  "B": [
    - *Relevance:* Prompt engineering is an emerging field, which tries to determine the optimal prompt structure to obtain LLM outputs tailored to certain requirements. At a deeper level the question is trying to establish whether it is worth it to invest time and resources in prompt engineering in an energy saving context.
    - *Results:* From the results we can surmise that while prompt engineering does have an effect on the code generated by the LLM, this change in output code does not necessarily imply an improvement in energy efficiency, especially when the machine running the code varies. This presents quite a challenge as a developer would need to know a priori what hardware the software would run on. Depending on the problem at hand this might not be possible. The findings evident from this study also seem to agree with the limited theory that is slowly being established.

  ],
  "C": [
    - *Research structure:* The research question and the following process follow a well-thought out plan; in line with the established computer science research pipeline, the inductive approach applied by the researchers is common in the software engineering field and is well suited for a niche and emerging field such as prompt engineering. The experiment choice is also well suited, as running in vivo experiments involving real-life like code bases would be outside the scope of a single papepr.
    - *Reproducibility:* Regarding the reproducibility of the experiment, the author does a good job of describing the setup used, both in hardware and testing framework, the author does not provide executables which could be used to replicate the energy usage measurements. Moreover some of the LLMs used are queried through API and are thus susceptible to architecture changes and updates which makes recreating results impossible. Another issue with running benchmarks with LLMs is their inherently non-deterministic behaviour, the code generated by prompting is not necessarily going to be the same at each prompt run. Multiple runs can be executed and statistics can be extracted from the obtained distribution, but the high variance between outputs makes the experiment less valuable.
  ],
  "D": (
    "1": [
      Write dilemma here... #lorem(10) 
    ],
    "2": [
      Write support here... #lorem(10) 
    ],
  )
)
