
= Introduction & Context

== Context & Background
Over the past few years, software engineering suffered a drastic change when it comes to the way that software is being produced and how fast it is being produced. One of the main factors that contributed to this drastic changed is represented by the emergence of Large Language Models (LLMs). Large Language Models were at first seen only as a tool that software developers used to replace traditional ways of learning like engaging in online communities (e.g. StackOverflow) @burtch_consequences_2024, that would end up taking hours of their time. Nowadays, they became actual coding assistants,that sometimes generate a large part of the code that goes into production, making software a lot more efficient to produce @peng_impact_2023, as software engineers only need to review the code that would have otherwise be written by themselves in a much longer time. Despite all these advantages, we have to raise the question that is being raised in every other major field, which is how sustainable the code that we are producing with these LLMs is.

== Problem Statement
Despite the high amount of research that evaluates LLM-generated code, most of it performs this evaluation in terms of its correctness. This is, of course, a necessity when it comes to deciding whether or not to start using LLMs when producing software. However, we also need to look at how energy efficient a correct solution generated by an LLM is, and to see if LLMs are able to give us correct solutions that not only are ready to be released into production, but are also meeting the criteria for an energy-efficient solution.

