
= Introduction & Context

== Context & Background

Over the past few years, software engineering has undergone a drastic change in how software is produced and how quickly it is produced. One of the main factors that contributed to this drastic change is the emergence of Large Language Models (LLMs). Large Language Models were at first seen only as a tool that software developers used to replace traditional ways of learning like engaging in online communities (e.g., StackOverflow) @burtch_consequences_2024, that would end up taking hours of their time. Nowadays, they became actual coding assistants that sometimes generate a large part of the code that goes into production, making software a lot more efficient to produce @peng_impact_2023, as software engineers only need to review the code that would have otherwise be written by themselves in a much longer time. Despite all these advantages, as concerns about sustainability emerge across numerous fields, it is important to examine whether code generated by LLMs is energy-efficient and sustainable in practice.

== Problem Statement

Although a substantial body of research has evaluated code generated by LLMs, most studies focus primarily on correctness. Assessing correctness is undoubtedly essential when determining whether LLMs can be reliably used for software development. However, correctness alone is not sufficient. We must also examine the energy efficiency of LLM-generated solutions and determine whether these models can produce code that is not only functionally correct and suitable for deployment in production environments, but also meets the requirements of energy-efficient software.

